### ISSUE TITLE
`ReferenceError: r is not defined` When trying to fetch URL's with redirect

### ISSUE THREAD

**Issue by jeanlescure** [afzaalace/metafetch#1]
```
./node_modules/metafetch/index.js:165
                                return r();
                                       ^

ReferenceError: r is not defined
```

https://github.com/afzaalace/metafetch/blob/master/index.js#L142
https://github.com/afzaalace/metafetch/blob/master/index.js#L165

Only happens when link redirects.

**NOTE:** This is the link that caused this error -> http://www.dianitica.com/
It redirects to -> http://dianitica.com/

**Comment by brahma-dev** [comment]
Fixed the bug in the latest commit. Please ensure you have the latest v1.2.4 from npm.

**Comment by jeanlescure** [comment]
Awesome, thanks!
