### ISSUE TITLE
breaks when we try fetching an image url

### ISSUE THREAD

**Issue by swapnil0545** [afzaalace/metafetch#10]
Hi,

I know we are not supposed to fetch any image(https://www.google.co.in/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png) with this library, but I want to catch the exception and don't want the library to break with this case.
It breaks in index.js : 
var $ = cheerio.load(body); 
> inside cheerios parse.js 
var oldParent = node.parent || node.root,
TypeError: Cannot read property 'parent' of undefined

Thank you.

**Comment by brahma-dev** [comment]
Please try the latest version.
