### ISSUE TITLE
UnhandledPromiseRejectionWarning -- Catch() missing

### ISSUE THREAD

**Issue by lajpatshah** [afzaalace/metafetch#11]
I received following error: 
On inspection I found that fetch() was written in promise without catch().
Can you please check this.

UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (http.js:42:10)
    at Request.request (/var/app/current/node_modules/superagent/lib/node/index.js:622:31)
    at Request.end (/var/app/current/node_modules/superagent/lib/node/index.js:764:8)
    at /var/app/current/node_modules/metafetch/index.js:203:74
    at new Promise (<anonymous>)
    at Object.Client.fetch (/var/app/current/node_modules/metafetch/index.js:138:9)

**Comment by brahma-dev** [comment]
@lajpatshah Can you add an example of the URL where it's failing.

**Comment by lajpatshah** [comment]
actually in my app a user had inserted malformed url. eg. 
`https://www.rediff.com/news/report/what-next-for-uddhav-thackeray/20191123.htm? var = uddhave next cm`
so here spaces in url are in unesacped form

**Comment by brahma-dev** [comment]
@lajpatshah That doesn't seem to be it considering that URLs get escaped. I am unable to reproduce the error condition with that URL.

**Comment by lajpatshah** [comment]
@brahma-dev i had tried with different url's and the issue persisted. I will send you couple of url's after checking at my end. Thanks.
