### ISSUE TITLE
UTF-8 characters in title and description not getting properly read

### ISSUE THREAD

**Issue by martinsotirov** [afzaalace/metafetch#13]
When I get the meta for this page https://www.hunziker-thalwil.ch/fr/hunziker-idep.htm metafetch returns the title as:

> Plate-forme d'�ducation digitale individuelle de Suisse | Hunziker AG Thalwil

The description is read as:

> La plate-forme digitale individuelle Edu est la premi�re solution suisse globale pour l'enseignement num�rique compl�mentaire conforme aux dispositions de la DSG et de l'ODASG.: hunziker-idep

**Comment by brahma-dev** [comment]
Thanks for catching this. Fixed in v2.0.3.
