### ISSUE TITLE
timeout not respected

### ISSUE THREAD

**Issue by kulinsj** [afzaalace/metafetch#16]
**Describe the bug**
For some URLs, the timeout param passed into the fetch call is not respected, the call never returns and never throws an error.

 - Node.js version: v16.15
 - OS & version:  MacOS Monterey 12.3.1

#### Actual behavior
Request goes into the void, never timing out.

#### Expected behavior
Request should time out after the specified amount of time.
...

#### Code to reproduce
(might need to try a different url, or set the timeout lower, but this one reproduces the issue _most_ of the time for me)
```js
metafetch.fetch(
  'https://www.seattletimes.com/nation-world/witnesses-myanmar-air-attack-kills-13-including-7-children/',
  {
    flags: { links: false, images: false },
    http: { timeout: 2500, headers: { 'Accept-Encoding': '*' }
  }
}).then(metadata => {
  console.log(metadata);
}).catch(e => {
  console.log(e);
});

```
Looking through the lib, it looks like the timeout param is not actually passed into the axios request
<img width="897" alt="Screen Shot 2022-09-20 at 2 45 01 PM" src="https://user-images.githubusercontent.com/1087009/191289638-4d96be77-4acc-4ffd-a3b2-fa405dbf6484.png">

adding `timeout: http_options.timeout,` to the axios request options objects seems to correct the issue

**Comment by brahma-dev** [comment]
@kulinsj Thanks for pointing that out. Will have to revisit the tests :). The new version is out on NPM.
