### ISSUE TITLE
Getting 409 error

### ISSUE THREAD

**Issue by lajpatshah** [afzaalace/metafetch#6]
I am trying to retrieve data from https://artplusmarketing.com/two-questions-at-the-heart-of-every-great-brand-strategy-c237180c3aa4

But I am getting 409 error. Same url when I try using another package (url-metadata.js) it is giving proper response.

Please inform how to correct this issue

**Comment by brahma-dev** [comment]
This is likely happening because Medium does not want you to spider their websites and detects it as a bot. I'll look into it ASAP.

**Comment by brahma-dev** [comment]
Fixed in v1.7.2
